import os

# ======================================================================
# CONFIGURAÇÕES GERAIS
# ======================================================================

PASTA = "NOME DA PASTA DO BANCO DE DADOS"
os.makedirs(PASTA, exist_ok=True)

# CONFIGURAÇÕES DE E-MAIL
EMAIL_REMETENTE = "SEU E-MAIL"
SENHA_APP_REMETENTE = "SUA SENHA"  # <<< TROCAR PELA SENHA DE APP DO GMAIL

# CONFIGURAÇÕES DO BOT DO TELEGRAM
BOT_TOKEN = "TOKEN DO TELEGRAM"  # <<< TROCAR PELO TOKEN DO BOT
CHAT_ID = "ID DO TELEGRAM"  # <<< TROCAR PELO CHAT ID

# CONFIGURAÇÕES DO MYSQL
MYSQL_HOST = "LOCAL DO SEU BANCOS DE DADOS"
MYSQL_USER = "USER DO BANCO DE DADOS"
MYSQL_PASSWORD = "SENHA DO BANCO DE DADOS"  # <<< TROCAR PELA SENHA DO MYSQL
MYSQL_DB = "NOME DO ARQUIVO DO BANCO DE DADOS"